alter table automation_actions drop constraint automation_actions_action_type_check;
alter table automation_actions add constraint automation_actions_action_type_check
  check (action_type in (
    'SEARCH_CONTACTS', 'GET_CONTACT', 'CREATE_CONTACT', 'UPDATE_CONTACT', 'UPSERT_CONTACT', 'DELETE_CONTACT', 'ADD_CONTACT_TAG', 'REMOVE_CONTACT_TAG', 'ASSIGN_LEAD',
    'SEARCH_OPPORTUNITIES', 'GET_OPPORTUNITY', 'CREATE_OPPORTUNITY', 'UPDATE_OPPORTUNITY', 'DELETE_OPPORTUNITY',
    'LIST_PIPELINES', 'CREATE_PIPELINE', 'UPDATE_PIPELINE', 'DELETE_PIPELINE', 'CREATE_PIPELINE_STAGE', 'UPDATE_PIPELINE_STAGE', 'DELETE_PIPELINE_STAGE',
    'LIST_TASKS', 'GET_TASK', 'CREATE_TASK', 'UPDATE_TASK', 'DELETE_TASK',
    'ADD_NOTE',
    'LIST_CUSTOM_FIELDS', 'CREATE_CUSTOM_FIELD', 'UPDATE_CUSTOM_FIELD', 'DELETE_CUSTOM_FIELD',
    'SEARCH_CONVERSATIONS', 'GET_CONVERSATION', 'SEND_MESSAGE',
    'LIST_CALENDARS'
  ));
